<?php

namespace Database\Seeders;

use App\Models\StoreItem;
use Illuminate\Database\Seeder;

class StoreItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // ════════════════════════════════════════════════════════════════
            // 1. DICE SKINS (type: dice_skin)
            // ════════════════════════════════════════════════════════════════
            [
                'item_key' => 'dice_classic',
                'name' => 'Classic Dice',
                'type' => 'dice_skin',
                'price' => 0,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Classic.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_chick',
                'name' => 'Chick',
                'type' => 'dice_skin',
                'price' => 5000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Chick.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_coffee',
                'name' => 'Coffee',
                'type' => 'dice_skin',
                'price' => 8000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Cofee.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_crystal',
                'name' => 'Crystal',
                'type' => 'dice_skin',
                'price' => 150,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Crystal.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_dessert',
                'name' => 'Dessert',
                'type' => 'dice_skin',
                'price' => 6500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Dessert.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_earth_power',
                'name' => 'Earth Power',
                'type' => 'dice_skin',
                'price' => 250,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Earth_power.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_fantasy_book',
                'name' => 'Fantasy Book',
                'type' => 'dice_skin',
                'price' => 12000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Fantasy_Book.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_ice_cream',
                'name' => 'Ice Cream',
                'type' => 'dice_skin',
                'price' => 7500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Icecream.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_leisure_kitty',
                'name' => 'Leisure Kitty',
                'type' => 'dice_skin',
                'price' => 180,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Leisure_kitty.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_rosy_life',
                'name' => 'Rosy Life',
                'type' => 'dice_skin',
                'price' => 10000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Rosy_Life.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_warm_campfire',
                'name' => 'Warm Campfire',
                'type' => 'dice_skin',
                'price' => 14000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Warm_Campfire.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_warrior_helmet',
                'name' => 'Warrior Helmet',
                'type' => 'dice_skin',
                'price' => 320,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Metal.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_wooden_case',
                'name' => 'Wooden Case',
                'type' => 'dice_skin',
                'price' => 4500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Wooden_Case.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_blessing_basket',
                'name' => 'Blessing Basket',
                'type' => 'dice_skin',
                'price' => 9500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/01_dice_skins_DiceTab/Blessing_Basket.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'dice_desert_hammer',
                'name' => 'Desert Hammer',
                'type' => 'dice_skin',
                'price' => 210,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
                'is_active' => true,
            ],

            // ════════════════════════════════════════════════════════════════
            // 2. TOKEN PIECE SETS (type: token_skin)
            // ════════════════════════════════════════════════════════════════
            [
                'item_key' => 'token_classic',
                'name' => 'Classic Pieces',
                'type' => 'token_skin',
                'price' => 0,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Classic.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_chick',
                'name' => 'Chick Set',
                'type' => 'token_skin',
                'price' => 5000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Chick-4.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_coffee',
                'name' => 'Coffee Set',
                'type' => 'token_skin',
                'price' => 8000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Cofee-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_blessing_basket',
                'name' => 'Blessing Basket Set',
                'type' => 'token_skin',
                'price' => 9500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Blessing_Basket-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_desert_hammer',
                'name' => 'Desert Hammer Set',
                'type' => 'token_skin',
                'price' => 210,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_earth_power',
                'name' => 'Earth Power Set',
                'type' => 'token_skin',
                'price' => 250,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Earth_power-7.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_fantasy_book',
                'name' => 'Fantasy Book Set',
                'type' => 'token_skin',
                'price' => 12000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Fantasy_Book-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_ice_cream',
                'name' => 'Ice Cream Set',
                'type' => 'token_skin',
                'price' => 7500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Icecream-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_leisure_kitty',
                'name' => 'Leisure Kitty Set',
                'type' => 'token_skin',
                'price' => 180,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Leisure_kitty-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_rosy_life',
                'name' => 'Rosy Life Set',
                'type' => 'token_skin',
                'price' => 10000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Rosy_Life-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_warm_campfire',
                'name' => 'Warm Campfire Set',
                'type' => 'token_skin',
                'price' => 14000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Warm_Campfire-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'token_wooden_case',
                'name' => 'Wooden Case Set',
                'type' => 'token_skin',
                'price' => 4500,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/03_piece_color_sets_TokenTab/Wooden_Case-2.png',
                'is_active' => true,
            ],

            // ════════════════════════════════════════════════════════════════
            // 3. BOARD THEMES (type: board_theme)
            // ════════════════════════════════════════════════════════════════
            [
                'item_key' => 'theme_classic',
                'name' => 'Classic Board',
                'type' => 'board_theme',
                'price' => 0,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/classic/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_dessert',
                'name' => 'Dessert Board',
                'type' => 'board_theme',
                'price' => 800,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/dessert/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_cloudy',
                'name' => 'Cloudy Board',
                'type' => 'board_theme',
                'price' => 1000,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/cloudy/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_paint',
                'name' => 'Paint Splash',
                'type' => 'board_theme',
                'price' => 1200,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/paint/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_warrior',
                'name' => 'Warrior Arena',
                'type' => 'board_theme',
                'price' => 1500,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/warrior/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_frostfire',
                'name' => 'Frostfire Board',
                'type' => 'board_theme',
                'price' => 1600,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/frostfire/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_enchanted',
                'name' => 'Enchanted Forest',
                'type' => 'board_theme',
                'price' => 1800,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/enchanted/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_lightning',
                'name' => 'Lightning Storm',
                'type' => 'board_theme',
                'price' => 2000,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/lightning/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_lucky_chest',
                'name' => 'Lucky Treasure',
                'type' => 'board_theme',
                'price' => 2200,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/lucky_chest/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_storm_lightning',
                'name' => 'High Voltage',
                'type' => 'board_theme',
                'price' => 2500,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/storm_lightning/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_indigo_wallpaper',
                'name' => 'Indigo Night',
                'type' => 'board_theme',
                'price' => 2800,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/indigo_wallpaper/preview.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'theme_letter_from_spring',
                'name' => 'Spring Bloom',
                'type' => 'board_theme',
                'price' => 3000,
                'currency_type' => 'coins',
                'image_url' => 'assets/themes/letter_from_spring/preview.png',
                'is_active' => true,
            ],

            // ════════════════════════════════════════════════════════════════
            // 4. SPEECH BUBBLES & AVATAR FRAMES (type: avatar_frame / bubble)
            // ════════════════════════════════════════════════════════════════
            [
                'item_key' => 'bubble_classic',
                'name' => 'Classic Frame',
                'type' => 'avatar_frame',
                'price' => 0,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-4.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_chick',
                'name' => 'Chick Bubble',
                'type' => 'bubble',
                'price' => 3000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Rectangle.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_crown_glow',
                'name' => 'Crown Glow',
                'type' => 'avatar_frame',
                'price' => 100,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-5.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_party',
                'name' => 'Party Bubble',
                'type' => 'bubble',
                'price' => 5000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-6.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_earth',
                'name' => 'Earth Frame',
                'type' => 'avatar_frame',
                'price' => 80,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-3.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_golden',
                'name' => 'Golden Frame',
                'type' => 'avatar_frame',
                'price' => 120,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-4.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_royal',
                'name' => 'Royal Frame',
                'type' => 'avatar_frame',
                'price' => 150,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-5.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_nature',
                'name' => 'Nature Frame',
                'type' => 'avatar_frame',
                'price' => 6000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-6.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_violet_star',
                'name' => 'Violet Star',
                'type' => 'avatar_frame',
                'price' => 90,
                'currency_type' => 'diamonds',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-7.png',
                'is_active' => true,
            ],
            [
                'item_key' => 'bubble_silver_wave',
                'name' => 'Silver Wave',
                'type' => 'avatar_frame',
                'price' => 7000,
                'currency_type' => 'coins',
                'image_url' => 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-8.png',
                'is_active' => true,
            ],
        ];

        foreach ($items as $data) {
            StoreItem::updateOrCreate(
                ['item_key' => $data['item_key']],
                $data
            );
        }
    }
}
