<?php

/**
 * Countries Configuration
 * 
 * Contains data for 240+ countries including:
 * - name: Full country name
 * - code: ISO 3166-1 alpha-2 code
 * - dial_code: International dialing code
 * - phone_pattern: Regex pattern for validating local phone number (without dial code)
 * - phone_length: Expected digits in local phone number
 * - phone_placeholder: Example format for UI display
 * - flag: Emoji flag
 */

return [
    ['name' => 'Afghanistan', 'code' => 'AF', 'dial_code' => '+93', 'phone_pattern' => '^7[0-9]{8}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXXXXXX', 'flag' => '🇦🇫'],
    ['name' => 'Albania', 'code' => 'AL', 'dial_code' => '+355', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '6X XXXXXXX', 'flag' => '🇦🇱'],
    ['name' => 'Algeria', 'code' => 'DZ', 'dial_code' => '+213', 'phone_pattern' => '^[5-7][0-9]{8}$', 'phone_length' => 9, 'phone_placeholder' => '5XX XXXXXX', 'flag' => '🇩🇿'],
    ['name' => 'Andorra', 'code' => 'AD', 'dial_code' => '+376', 'phone_pattern' => '^[0-9]{6}$', 'phone_length' => 6, 'phone_placeholder' => 'XXXXXX', 'flag' => '🇦🇩'],
    ['name' => 'Angola', 'code' => 'AO', 'dial_code' => '+244', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇦🇴'],
    ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'dial_code' => '+1-268', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇦🇬'],
    ['name' => 'Argentina', 'code' => 'AR', 'dial_code' => '+54', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '11 XXXX XXXX', 'flag' => '🇦🇷'],
    ['name' => 'Armenia', 'code' => 'AM', 'dial_code' => '+374', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => 'XX XXXXXX', 'flag' => '🇦🇲'],
    ['name' => 'Australia', 'code' => 'AU', 'dial_code' => '+61', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '4XX XXX XXX', 'flag' => '🇦🇺'],
    ['name' => 'Austria', 'code' => 'AT', 'dial_code' => '+43', 'phone_pattern' => '^[0-9]{10,11}$', 'phone_length' => 10, 'phone_placeholder' => '6XX XXXXXXX', 'flag' => '🇦🇹'],
    ['name' => 'Azerbaijan', 'code' => 'AZ', 'dial_code' => '+994', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇦🇿'],
    ['name' => 'Bahamas', 'code' => 'BS', 'dial_code' => '+1-242', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇧🇸'],
    ['name' => 'Bahrain', 'code' => 'BH', 'dial_code' => '+973', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '3XXX XXXX', 'flag' => '🇧🇭'],
    ['name' => 'Bangladesh', 'code' => 'BD', 'dial_code' => '+880', 'phone_pattern' => '^1[0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '1XXX XXXXXX', 'flag' => '🇧🇩'],
    ['name' => 'Barbados', 'code' => 'BB', 'dial_code' => '+1-246', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇧🇧'],
    ['name' => 'Belarus', 'code' => 'BY', 'dial_code' => '+375', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '29 XXX XXXX', 'flag' => '🇧🇾'],
    ['name' => 'Belgium', 'code' => 'BE', 'dial_code' => '+32', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '4XX XX XX XX', 'flag' => '🇧🇪'],
    ['name' => 'Belize', 'code' => 'BZ', 'dial_code' => '+501', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '6XX XXXX', 'flag' => '🇧🇿'],
    ['name' => 'Benin', 'code' => 'BJ', 'dial_code' => '+229', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9X XXXXXX', 'flag' => '🇧🇯'],
    ['name' => 'Bhutan', 'code' => 'BT', 'dial_code' => '+975', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '17 XXXXXX', 'flag' => '🇧🇹'],
    ['name' => 'Bolivia', 'code' => 'BO', 'dial_code' => '+591', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7XXX XXXX', 'flag' => '🇧🇴'],
    ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'dial_code' => '+387', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXX XXX', 'flag' => '🇧🇦'],
    ['name' => 'Botswana', 'code' => 'BW', 'dial_code' => '+267', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇧🇼'],
    ['name' => 'Brazil', 'code' => 'BR', 'dial_code' => '+55', 'phone_pattern' => '^[0-9]{10,11}$', 'phone_length' => 11, 'phone_placeholder' => '11 9XXXX XXXX', 'flag' => '🇧🇷'],
    ['name' => 'Brunei', 'code' => 'BN', 'dial_code' => '+673', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇧🇳'],
    ['name' => 'Bulgaria', 'code' => 'BG', 'dial_code' => '+359', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '8X XXXXXXX', 'flag' => '🇧🇬'],
    ['name' => 'Burkina Faso', 'code' => 'BF', 'dial_code' => '+226', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇧🇫'],
    ['name' => 'Burundi', 'code' => 'BI', 'dial_code' => '+257', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇧🇮'],
    ['name' => 'Cambodia', 'code' => 'KH', 'dial_code' => '+855', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇰🇭'],
    ['name' => 'Cameroon', 'code' => 'CM', 'dial_code' => '+237', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXXXXX', 'flag' => '🇨🇲'],
    ['name' => 'Canada', 'code' => 'CA', 'dial_code' => '+1', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => 'XXX XXX XXXX', 'flag' => '🇨🇦'],
    ['name' => 'Cape Verde', 'code' => 'CV', 'dial_code' => '+238', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '9XX XXXX', 'flag' => '🇨🇻'],
    ['name' => 'Central African Republic', 'code' => 'CF', 'dial_code' => '+236', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇨🇫'],
    ['name' => 'Chad', 'code' => 'TD', 'dial_code' => '+235', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇹🇩'],
    ['name' => 'Chile', 'code' => 'CL', 'dial_code' => '+56', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9 XXXX XXXX', 'flag' => '🇨🇱'],
    ['name' => 'China', 'code' => 'CN', 'dial_code' => '+86', 'phone_pattern' => '^1[0-9]{10}$', 'phone_length' => 11, 'phone_placeholder' => '1XX XXXX XXXX', 'flag' => '🇨🇳'],
    ['name' => 'Colombia', 'code' => 'CO', 'dial_code' => '+57', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '3XX XXX XXXX', 'flag' => '🇨🇴'],
    ['name' => 'Comoros', 'code' => 'KM', 'dial_code' => '+269', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '3XX XXXX', 'flag' => '🇰🇲'],
    ['name' => 'Congo (DRC)', 'code' => 'CD', 'dial_code' => '+243', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇨🇩'],
    ['name' => 'Congo (Republic)', 'code' => 'CG', 'dial_code' => '+242', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '0X XXX XXXX', 'flag' => '🇨🇬'],
    ['name' => 'Costa Rica', 'code' => 'CR', 'dial_code' => '+506', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '8XXX XXXX', 'flag' => '🇨🇷'],
    ['name' => 'Croatia', 'code' => 'HR', 'dial_code' => '+385', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇭🇷'],
    ['name' => 'Cuba', 'code' => 'CU', 'dial_code' => '+53', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇨🇺'],
    ['name' => 'Cyprus', 'code' => 'CY', 'dial_code' => '+357', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9X XXXXXX', 'flag' => '🇨🇾'],
    ['name' => 'Czech Republic', 'code' => 'CZ', 'dial_code' => '+420', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXX XXX', 'flag' => '🇨🇿'],
    ['name' => 'Denmark', 'code' => 'DK', 'dial_code' => '+45', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => 'XX XX XX XX', 'flag' => '🇩🇰'],
    ['name' => 'Djibouti', 'code' => 'DJ', 'dial_code' => '+253', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '77 XXXXXX', 'flag' => '🇩🇯'],
    ['name' => 'Dominica', 'code' => 'DM', 'dial_code' => '+1-767', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇩🇲'],
    ['name' => 'Dominican Republic', 'code' => 'DO', 'dial_code' => '+1-809', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇩🇴'],
    ['name' => 'Ecuador', 'code' => 'EC', 'dial_code' => '+593', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇪🇨'],
    ['name' => 'Egypt', 'code' => 'EG', 'dial_code' => '+20', 'phone_pattern' => '^1[0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '10 XXXX XXXX', 'flag' => '🇪🇬'],
    ['name' => 'El Salvador', 'code' => 'SV', 'dial_code' => '+503', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7XXX XXXX', 'flag' => '🇸🇻'],
    ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'dial_code' => '+240', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '2XX XXXXXX', 'flag' => '🇬🇶'],
    ['name' => 'Eritrea', 'code' => 'ER', 'dial_code' => '+291', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇪🇷'],
    ['name' => 'Estonia', 'code' => 'EE', 'dial_code' => '+372', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇪🇪'],
    ['name' => 'Eswatini', 'code' => 'SZ', 'dial_code' => '+268', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7XXX XXXX', 'flag' => '🇸🇿'],
    ['name' => 'Ethiopia', 'code' => 'ET', 'dial_code' => '+251', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇪🇹'],
    ['name' => 'Fiji', 'code' => 'FJ', 'dial_code' => '+679', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇫🇯'],
    ['name' => 'Finland', 'code' => 'FI', 'dial_code' => '+358', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '40 XXX XXXX', 'flag' => '🇫🇮'],
    ['name' => 'France', 'code' => 'FR', 'dial_code' => '+33', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6 XX XX XX XX', 'flag' => '🇫🇷'],
    ['name' => 'Gabon', 'code' => 'GA', 'dial_code' => '+241', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '0X XXXXXX', 'flag' => '🇬🇦'],
    ['name' => 'Gambia', 'code' => 'GM', 'dial_code' => '+220', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇬🇲'],
    ['name' => 'Georgia', 'code' => 'GE', 'dial_code' => '+995', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5XX XXXXXX', 'flag' => '🇬🇪'],
    ['name' => 'Germany', 'code' => 'DE', 'dial_code' => '+49', 'phone_pattern' => '^[0-9]{10,11}$', 'phone_length' => 11, 'phone_placeholder' => '15X XXXXXXXX', 'flag' => '🇩🇪'],
    ['name' => 'Ghana', 'code' => 'GH', 'dial_code' => '+233', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '2X XXX XXXX', 'flag' => '🇬🇭'],
    ['name' => 'Greece', 'code' => 'GR', 'dial_code' => '+30', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '69X XXX XXXX', 'flag' => '🇬🇷'],
    ['name' => 'Grenada', 'code' => 'GD', 'dial_code' => '+1-473', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇬🇩'],
    ['name' => 'Guatemala', 'code' => 'GT', 'dial_code' => '+502', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇬🇹'],
    ['name' => 'Guinea', 'code' => 'GN', 'dial_code' => '+224', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXXXXX', 'flag' => '🇬🇳'],
    ['name' => 'Guinea-Bissau', 'code' => 'GW', 'dial_code' => '+245', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '9XX XXXX', 'flag' => '🇬🇼'],
    ['name' => 'Guyana', 'code' => 'GY', 'dial_code' => '+592', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '6XX XXXX', 'flag' => '🇬🇾'],
    ['name' => 'Haiti', 'code' => 'HT', 'dial_code' => '+509', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '3XXX XXXX', 'flag' => '🇭🇹'],
    ['name' => 'Honduras', 'code' => 'HN', 'dial_code' => '+504', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9XXX XXXX', 'flag' => '🇭🇳'],
    ['name' => 'Hong Kong', 'code' => 'HK', 'dial_code' => '+852', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇭🇰'],
    ['name' => 'Hungary', 'code' => 'HU', 'dial_code' => '+36', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '20 XXX XXXX', 'flag' => '🇭🇺'],
    ['name' => 'Iceland', 'code' => 'IS', 'dial_code' => '+354', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '8XX XXXX', 'flag' => '🇮🇸'],
    ['name' => 'India', 'code' => 'IN', 'dial_code' => '+91', 'phone_pattern' => '^[6-9][0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '9XXX XXXXXX', 'flag' => '🇮🇳'],
    ['name' => 'Indonesia', 'code' => 'ID', 'dial_code' => '+62', 'phone_pattern' => '^[0-9]{9,12}$', 'phone_length' => 12, 'phone_placeholder' => '8XX XXXX XXXX', 'flag' => '🇮🇩'],
    ['name' => 'Iran', 'code' => 'IR', 'dial_code' => '+98', 'phone_pattern' => '^9[0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '9XX XXX XXXX', 'flag' => '🇮🇷'],
    ['name' => 'Iraq', 'code' => 'IQ', 'dial_code' => '+964', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '7XX XXX XXXX', 'flag' => '🇮🇶'],
    ['name' => 'Ireland', 'code' => 'IE', 'dial_code' => '+353', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '8X XXX XXXX', 'flag' => '🇮🇪'],
    ['name' => 'Israel', 'code' => 'IL', 'dial_code' => '+972', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇮🇱'],
    ['name' => 'Italy', 'code' => 'IT', 'dial_code' => '+39', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '3XX XXX XXXX', 'flag' => '🇮🇹'],
    ['name' => 'Ivory Coast', 'code' => 'CI', 'dial_code' => '+225', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '0X XXXX XXXX', 'flag' => '🇨🇮'],
    ['name' => 'Jamaica', 'code' => 'JM', 'dial_code' => '+1-876', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇯🇲'],
    ['name' => 'Japan', 'code' => 'JP', 'dial_code' => '+81', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '80 XXXX XXXX', 'flag' => '🇯🇵'],
    ['name' => 'Jordan', 'code' => 'JO', 'dial_code' => '+962', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇯🇴'],
    ['name' => 'Kazakhstan', 'code' => 'KZ', 'dial_code' => '+7', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '7XX XXX XXXX', 'flag' => '🇰🇿'],
    ['name' => 'Kenya', 'code' => 'KE', 'dial_code' => '+254', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇰🇪'],
    ['name' => 'Kiribati', 'code' => 'KI', 'dial_code' => '+686', 'phone_pattern' => '^[0-9]{5,8}$', 'phone_length' => 8, 'phone_placeholder' => 'XXXX XXXX', 'flag' => '🇰🇮'],
    ['name' => 'Kosovo', 'code' => 'XK', 'dial_code' => '+383', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '4X XXXXXX', 'flag' => '🇽🇰'],
    ['name' => 'Kuwait', 'code' => 'KW', 'dial_code' => '+965', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇰🇼'],
    ['name' => 'Kyrgyzstan', 'code' => 'KG', 'dial_code' => '+996', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇰🇬'],
    ['name' => 'Laos', 'code' => 'LA', 'dial_code' => '+856', 'phone_pattern' => '^[0-9]{8,10}$', 'phone_length' => 10, 'phone_placeholder' => '20 XXXX XXXX', 'flag' => '🇱🇦'],
    ['name' => 'Latvia', 'code' => 'LV', 'dial_code' => '+371', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '2X XXXXXX', 'flag' => '🇱🇻'],
    ['name' => 'Lebanon', 'code' => 'LB', 'dial_code' => '+961', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇱🇧'],
    ['name' => 'Lesotho', 'code' => 'LS', 'dial_code' => '+266', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5X XXXXXX', 'flag' => '🇱🇸'],
    ['name' => 'Liberia', 'code' => 'LR', 'dial_code' => '+231', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇱🇷'],
    ['name' => 'Libya', 'code' => 'LY', 'dial_code' => '+218', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXXXXXX', 'flag' => '🇱🇾'],
    ['name' => 'Liechtenstein', 'code' => 'LI', 'dial_code' => '+423', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '6XX XXXX', 'flag' => '🇱🇮'],
    ['name' => 'Lithuania', 'code' => 'LT', 'dial_code' => '+370', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇱🇹'],
    ['name' => 'Luxembourg', 'code' => 'LU', 'dial_code' => '+352', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXXXXX', 'flag' => '🇱🇺'],
    ['name' => 'Macau', 'code' => 'MO', 'dial_code' => '+853', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6XXX XXXX', 'flag' => '🇲🇴'],
    ['name' => 'Madagascar', 'code' => 'MG', 'dial_code' => '+261', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '3X XX XXXXX', 'flag' => '🇲🇬'],
    ['name' => 'Malawi', 'code' => 'MW', 'dial_code' => '+265', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇲🇼'],
    ['name' => 'Malaysia', 'code' => 'MY', 'dial_code' => '+60', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '1X XXXX XXXX', 'flag' => '🇲🇾'],
    ['name' => 'Maldives', 'code' => 'MV', 'dial_code' => '+960', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇲🇻'],
    ['name' => 'Mali', 'code' => 'ML', 'dial_code' => '+223', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇲🇱'],
    ['name' => 'Malta', 'code' => 'MT', 'dial_code' => '+356', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9XXX XXXX', 'flag' => '🇲🇹'],
    ['name' => 'Marshall Islands', 'code' => 'MH', 'dial_code' => '+692', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇲🇭'],
    ['name' => 'Mauritania', 'code' => 'MR', 'dial_code' => '+222', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => 'XX XXXXXX', 'flag' => '🇲🇷'],
    ['name' => 'Mauritius', 'code' => 'MU', 'dial_code' => '+230', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '5XXX XXXX', 'flag' => '🇲🇺'],
    ['name' => 'Mexico', 'code' => 'MX', 'dial_code' => '+52', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '55 XXXX XXXX', 'flag' => '🇲🇽'],
    ['name' => 'Micronesia', 'code' => 'FM', 'dial_code' => '+691', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇫🇲'],
    ['name' => 'Moldova', 'code' => 'MD', 'dial_code' => '+373', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇲🇩'],
    ['name' => 'Monaco', 'code' => 'MC', 'dial_code' => '+377', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇲🇨'],
    ['name' => 'Mongolia', 'code' => 'MN', 'dial_code' => '+976', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '8X XXXXXX', 'flag' => '🇲🇳'],
    ['name' => 'Montenegro', 'code' => 'ME', 'dial_code' => '+382', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇲🇪'],
    ['name' => 'Morocco', 'code' => 'MA', 'dial_code' => '+212', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXXXXX', 'flag' => '🇲🇦'],
    ['name' => 'Mozambique', 'code' => 'MZ', 'dial_code' => '+258', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '8X XXXXXXX', 'flag' => '🇲🇿'],
    ['name' => 'Myanmar', 'code' => 'MM', 'dial_code' => '+95', 'phone_pattern' => '^[0-9]{8,10}$', 'phone_length' => 10, 'phone_placeholder' => '9XXX XXXXXX', 'flag' => '🇲🇲'],
    ['name' => 'Namibia', 'code' => 'NA', 'dial_code' => '+264', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '8X XXXXXXX', 'flag' => '🇳🇦'],
    ['name' => 'Nauru', 'code' => 'NR', 'dial_code' => '+674', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '555 XXXX', 'flag' => '🇳🇷'],
    ['name' => 'Nepal', 'code' => 'NP', 'dial_code' => '+977', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '98XX XXXXXX', 'flag' => '🇳🇵'],
    ['name' => 'Netherlands', 'code' => 'NL', 'dial_code' => '+31', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6 XXXX XXXX', 'flag' => '🇳🇱'],
    ['name' => 'New Zealand', 'code' => 'NZ', 'dial_code' => '+64', 'phone_pattern' => '^[0-9]{8,10}$', 'phone_length' => 10, 'phone_placeholder' => '2X XXXX XXXX', 'flag' => '🇳🇿'],
    ['name' => 'Nicaragua', 'code' => 'NI', 'dial_code' => '+505', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '8XXX XXXX', 'flag' => '🇳🇮'],
    ['name' => 'Niger', 'code' => 'NE', 'dial_code' => '+227', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9X XXXXXX', 'flag' => '🇳🇪'],
    ['name' => 'Nigeria', 'code' => 'NG', 'dial_code' => '+234', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '80X XXX XXXX', 'flag' => '🇳🇬'],
    ['name' => 'North Korea', 'code' => 'KP', 'dial_code' => '+850', 'phone_pattern' => '^[0-9]{8,10}$', 'phone_length' => 10, 'phone_placeholder' => '19X XXX XXXX', 'flag' => '🇰🇵'],
    ['name' => 'North Macedonia', 'code' => 'MK', 'dial_code' => '+389', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇲🇰'],
    ['name' => 'Norway', 'code' => 'NO', 'dial_code' => '+47', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '4XX XX XXX', 'flag' => '🇳🇴'],
    ['name' => 'Oman', 'code' => 'OM', 'dial_code' => '+968', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9XXX XXXX', 'flag' => '🇴🇲'],
    ['name' => 'Pakistan', 'code' => 'PK', 'dial_code' => '+92', 'phone_pattern' => '^3[0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '3XX XXXXXXX', 'flag' => '🇵🇰'],
    ['name' => 'Palau', 'code' => 'PW', 'dial_code' => '+680', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇵🇼'],
    ['name' => 'Palestine', 'code' => 'PS', 'dial_code' => '+970', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇵🇸'],
    ['name' => 'Panama', 'code' => 'PA', 'dial_code' => '+507', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '6XXX XXXX', 'flag' => '🇵🇦'],
    ['name' => 'Papua New Guinea', 'code' => 'PG', 'dial_code' => '+675', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7XXX XXXX', 'flag' => '🇵🇬'],
    ['name' => 'Paraguay', 'code' => 'PY', 'dial_code' => '+595', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇵🇾'],
    ['name' => 'Peru', 'code' => 'PE', 'dial_code' => '+51', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXX XXX', 'flag' => '🇵🇪'],
    ['name' => 'Philippines', 'code' => 'PH', 'dial_code' => '+63', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '9XX XXX XXXX', 'flag' => '🇵🇭'],
    ['name' => 'Poland', 'code' => 'PL', 'dial_code' => '+48', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5XX XXX XXX', 'flag' => '🇵🇱'],
    ['name' => 'Portugal', 'code' => 'PT', 'dial_code' => '+351', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇵🇹'],
    ['name' => 'Qatar', 'code' => 'QA', 'dial_code' => '+974', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '3XXX XXXX', 'flag' => '🇶🇦'],
    ['name' => 'Romania', 'code' => 'RO', 'dial_code' => '+40', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXX XXX', 'flag' => '🇷🇴'],
    ['name' => 'Russia', 'code' => 'RU', 'dial_code' => '+7', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '9XX XXX XXXX', 'flag' => '🇷🇺'],
    ['name' => 'Rwanda', 'code' => 'RW', 'dial_code' => '+250', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇷🇼'],
    ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'dial_code' => '+1-869', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇰🇳'],
    ['name' => 'Saint Lucia', 'code' => 'LC', 'dial_code' => '+1-758', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇱🇨'],
    ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'dial_code' => '+1-784', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇻🇨'],
    ['name' => 'Samoa', 'code' => 'WS', 'dial_code' => '+685', 'phone_pattern' => '^[0-9]{5,7}$', 'phone_length' => 7, 'phone_placeholder' => '7X XXXXX', 'flag' => '🇼🇸'],
    ['name' => 'San Marino', 'code' => 'SM', 'dial_code' => '+378', 'phone_pattern' => '^[0-9]{8,10}$', 'phone_length' => 10, 'phone_placeholder' => '6X XXXX XXXX', 'flag' => '🇸🇲'],
    ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'dial_code' => '+239', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '9XX XXXX', 'flag' => '🇸🇹'],
    ['name' => 'Saudi Arabia', 'code' => 'SA', 'dial_code' => '+966', 'phone_pattern' => '^5[0-9]{8}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇸🇦'],
    ['name' => 'Senegal', 'code' => 'SN', 'dial_code' => '+221', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇸🇳'],
    ['name' => 'Serbia', 'code' => 'RS', 'dial_code' => '+381', 'phone_pattern' => '^[0-9]{8,9}$', 'phone_length' => 9, 'phone_placeholder' => '6X XXXXXXX', 'flag' => '🇷🇸'],
    ['name' => 'Seychelles', 'code' => 'SC', 'dial_code' => '+248', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '2XX XXXX', 'flag' => '🇸🇨'],
    ['name' => 'Sierra Leone', 'code' => 'SL', 'dial_code' => '+232', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '7X XXXXXX', 'flag' => '🇸🇱'],
    ['name' => 'Singapore', 'code' => 'SG', 'dial_code' => '+65', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '8XXX XXXX', 'flag' => '🇸🇬'],
    ['name' => 'Slovakia', 'code' => 'SK', 'dial_code' => '+421', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXX XXX', 'flag' => '🇸🇰'],
    ['name' => 'Slovenia', 'code' => 'SI', 'dial_code' => '+386', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '3X XXXXXX', 'flag' => '🇸🇮'],
    ['name' => 'Solomon Islands', 'code' => 'SB', 'dial_code' => '+677', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇸🇧'],
    ['name' => 'Somalia', 'code' => 'SO', 'dial_code' => '+252', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇸🇴'],
    ['name' => 'South Africa', 'code' => 'ZA', 'dial_code' => '+27', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇿🇦'],
    ['name' => 'South Korea', 'code' => 'KR', 'dial_code' => '+82', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '10 XXXX XXXX', 'flag' => '🇰🇷'],
    ['name' => 'South Sudan', 'code' => 'SS', 'dial_code' => '+211', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇸🇸'],
    ['name' => 'Spain', 'code' => 'ES', 'dial_code' => '+34', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '6XX XXX XXX', 'flag' => '🇪🇸'],
    ['name' => 'Sri Lanka', 'code' => 'LK', 'dial_code' => '+94', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇱🇰'],
    ['name' => 'Sudan', 'code' => 'SD', 'dial_code' => '+249', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXXXXXX', 'flag' => '🇸🇩'],
    ['name' => 'Suriname', 'code' => 'SR', 'dial_code' => '+597', 'phone_pattern' => '^[0-9]{6,7}$', 'phone_length' => 7, 'phone_placeholder' => '8XX XXXX', 'flag' => '🇸🇷'],
    ['name' => 'Sweden', 'code' => 'SE', 'dial_code' => '+46', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇸🇪'],
    ['name' => 'Switzerland', 'code' => 'CH', 'dial_code' => '+41', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXX XXXX', 'flag' => '🇨🇭'],
    ['name' => 'Syria', 'code' => 'SY', 'dial_code' => '+963', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇸🇾'],
    ['name' => 'Taiwan', 'code' => 'TW', 'dial_code' => '+886', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇹🇼'],
    ['name' => 'Tajikistan', 'code' => 'TJ', 'dial_code' => '+992', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9XX XXXXXX', 'flag' => '🇹🇯'],
    ['name' => 'Tanzania', 'code' => 'TZ', 'dial_code' => '+255', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇹🇿'],
    ['name' => 'Thailand', 'code' => 'TH', 'dial_code' => '+66', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '8X XXXX XXX', 'flag' => '🇹🇭'],
    ['name' => 'Timor-Leste', 'code' => 'TL', 'dial_code' => '+670', 'phone_pattern' => '^[0-9]{7,8}$', 'phone_length' => 8, 'phone_placeholder' => '7XXX XXXX', 'flag' => '🇹🇱'],
    ['name' => 'Togo', 'code' => 'TG', 'dial_code' => '+228', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9X XXXXXX', 'flag' => '🇹🇬'],
    ['name' => 'Tonga', 'code' => 'TO', 'dial_code' => '+676', 'phone_pattern' => '^[0-9]{5,7}$', 'phone_length' => 7, 'phone_placeholder' => '7XX XXXX', 'flag' => '🇹🇴'],
    ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'dial_code' => '+1-868', 'phone_pattern' => '^[0-9]{7}$', 'phone_length' => 7, 'phone_placeholder' => 'XXX XXXX', 'flag' => '🇹🇹'],
    ['name' => 'Tunisia', 'code' => 'TN', 'dial_code' => '+216', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '2X XXXXXX', 'flag' => '🇹🇳'],
    ['name' => 'Turkey', 'code' => 'TR', 'dial_code' => '+90', 'phone_pattern' => '^5[0-9]{9}$', 'phone_length' => 10, 'phone_placeholder' => '5XX XXX XXXX', 'flag' => '🇹🇷'],
    ['name' => 'Turkmenistan', 'code' => 'TM', 'dial_code' => '+993', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '6X XXXXXX', 'flag' => '🇹🇲'],
    ['name' => 'Tuvalu', 'code' => 'TV', 'dial_code' => '+688', 'phone_pattern' => '^[0-9]{5,6}$', 'phone_length' => 6, 'phone_placeholder' => '9X XXXX', 'flag' => '🇹🇻'],
    ['name' => 'Uganda', 'code' => 'UG', 'dial_code' => '+256', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇺🇬'],
    ['name' => 'Ukraine', 'code' => 'UA', 'dial_code' => '+380', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇺🇦'],
    ['name' => 'United Arab Emirates', 'code' => 'AE', 'dial_code' => '+971', 'phone_pattern' => '^5[0-9]{8}$', 'phone_length' => 9, 'phone_placeholder' => '5X XXX XXXX', 'flag' => '🇦🇪'],
    ['name' => 'United Kingdom', 'code' => 'GB', 'dial_code' => '+44', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '7XXX XXXXXX', 'flag' => '🇬🇧'],
    ['name' => 'United States', 'code' => 'US', 'dial_code' => '+1', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => 'XXX XXX XXXX', 'flag' => '🇺🇸'],
    ['name' => 'Uruguay', 'code' => 'UY', 'dial_code' => '+598', 'phone_pattern' => '^[0-9]{8}$', 'phone_length' => 8, 'phone_placeholder' => '9X XXXXXX', 'flag' => '🇺🇾'],
    ['name' => 'Uzbekistan', 'code' => 'UZ', 'dial_code' => '+998', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇺🇿'],
    ['name' => 'Vanuatu', 'code' => 'VU', 'dial_code' => '+678', 'phone_pattern' => '^[0-9]{5,7}$', 'phone_length' => 7, 'phone_placeholder' => '5XX XXXX', 'flag' => '🇻🇺'],
    ['name' => 'Vatican City', 'code' => 'VA', 'dial_code' => '+379', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '06 XXXX XXXX', 'flag' => '🇻🇦'],
    ['name' => 'Venezuela', 'code' => 'VE', 'dial_code' => '+58', 'phone_pattern' => '^[0-9]{10}$', 'phone_length' => 10, 'phone_placeholder' => '4XX XXX XXXX', 'flag' => '🇻🇪'],
    ['name' => 'Vietnam', 'code' => 'VN', 'dial_code' => '+84', 'phone_pattern' => '^[0-9]{9,10}$', 'phone_length' => 10, 'phone_placeholder' => '9X XXX XXXX', 'flag' => '🇻🇳'],
    ['name' => 'Yemen', 'code' => 'YE', 'dial_code' => '+967', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7XX XXXXXX', 'flag' => '🇾🇪'],
    ['name' => 'Zambia', 'code' => 'ZM', 'dial_code' => '+260', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '9X XXXXXXX', 'flag' => '🇿🇲'],
    ['name' => 'Zimbabwe', 'code' => 'ZW', 'dial_code' => '+263', 'phone_pattern' => '^[0-9]{9}$', 'phone_length' => 9, 'phone_placeholder' => '7X XXXXXXX', 'flag' => '🇿🇼'],
];
